package main

import (
	"google-photos-sync/di"
	"google-photos-sync/pkg/graceful"

	_ "google-photos-sync/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Google photos sync account
// @version 1.0
// @host localhost:8080
// @BasePath /api
// @schemes http
func main() {
	container := di.Build()

	err := container.Invoke(func(application graceful.Application) {
		application.RunAndWait()
	})

	if err != nil {
		panic(err)
	}
}
